name: ci-bowfolios

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./app

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: Read release file
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./app/.meteor/release
      - name: Echo release
        run: echo ${{ steps.package.outputs.content }}
      - id: get-version-number
        uses: actions/github-script@0.9.0
        with:
          script: |
            const id = context.payload.client_payload.value.split('@')[1]
            core.setOutput('id', id)
      - run: echo "${{steps.get-version-number.outputs.id}}"
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.11.1'
      - run: meteor npm install
      - run: meteor npm run lint
      - run: meteor npm run testcafe-ci
